"""Media generation pass for interactive courses.

After the concept JSON is produced, this walks the concept and fills in real
asset URLs for the media prompts emitted by the generator:

- images / hotspot images / dialogue avatars -> Pixverse text-to-image
- short clips -> Pixverse text-to-video
- narration -> Google Cloud Text-to-Speech (MP3)

Generated bytes are uploaded to the course's MinIO prefix under `assets/` and the
block is given a *relative* `url` (resolved against the course's index.html in the
iframe). Everything is best-effort and bounded by per-course caps: any failure
(missing key, insufficient credits, bad prompt) is logged and the block keeps its
prompt so the renderer shows a graceful placeholder instead of breaking.
"""

import asyncio
import base64
import hashlib
import logging
import uuid
from collections.abc import Awaitable, Callable

import httpx

from src.config.settings import settings
from src.db.minio import put_bytes

logger = logging.getLogger(__name__)

ProgressCb = Callable[[str, int], Awaitable[None]]


class MediaError(RuntimeError):
    pass


class PixverseClient:
    """Async client for Pixverse text-to-image and text-to-video."""

    def __init__(self, api_key: str | None = None, base_url: str | None = None) -> None:
        self.api_key = api_key or settings.pixverse_api_key
        self.base_url = (base_url or settings.pixverse_api_base_url).rstrip("/")

    @property
    def enabled(self) -> bool:
        return bool(self.api_key)

    def _headers(self) -> dict[str, str]:
        return {
            "API-KEY": self.api_key,
            "Ai-trace-id": str(uuid.uuid4()),
            "Content-Type": "application/json",
        }

    @staticmethod
    def _resp_ok(data: dict) -> dict:
        if data.get("ErrCode") not in (0, None):
            raise MediaError(f"pixverse error {data.get('ErrCode')}: {data.get('ErrMsg')}")
        return data.get("Resp") or {}

    async def _download(self, client: httpx.AsyncClient, url: str) -> bytes:
        r = await client.get(url)
        if r.status_code >= 400:
            raise MediaError(f"download failed [{r.status_code}] {url}")
        return r.content

    async def generate_image(self, prompt: str, aspect_ratio: str = "16:9") -> bytes:
        body = {
            "prompt": prompt,
            "model": settings.pixverse_image_model,
            "aspect_ratio": aspect_ratio,
            "quality": "1080p",
        }
        async with httpx.AsyncClient(timeout=60) as client:
            r = await client.post(
                f"{self.base_url}{settings.pixverse_image_path}",
                json=body,
                headers=self._headers(),
            )
            if r.status_code >= 400:
                raise MediaError(f"image create failed [{r.status_code}]: {r.text[:200]}")
            resp = self._resp_ok(r.json())
            # Some responses return a URL synchronously; otherwise poll by id.
            url = resp.get("url") or resp.get("Url")
            image_id = resp.get("image_id") or resp.get("ImgId") or resp.get("img_id")
            if not url and image_id is not None:
                url = await self._poll_image(client, image_id)
            if not url:
                raise MediaError("image generation returned no url")
            return await self._download(client, url)

    async def _poll_image(self, client: httpx.AsyncClient, image_id: int) -> str:
        waited = 0
        while waited < settings.media_poll_timeout:
            r = await client.get(
                f"{self.base_url}/openapi/v2/image/result/{image_id}",
                headers=self._headers(),
            )
            if r.status_code < 400:
                resp = self._resp_ok(r.json())
                url = resp.get("url") or resp.get("Url")
                if url:
                    return url
            await asyncio.sleep(5)
            waited += 5
        raise MediaError(f"image {image_id} timed out")

    async def generate_video(self, prompt: str, aspect_ratio: str = "16:9") -> bytes:
        body = {
            "prompt": prompt,
            "model": settings.pixverse_video_model,
            "aspect_ratio": aspect_ratio,
            "duration": 5,
            "quality": "540p",
            "motion_mode": "normal",
        }
        async with httpx.AsyncClient(timeout=60) as client:
            r = await client.post(
                f"{self.base_url}/openapi/v2/video/text/generate",
                json=body,
                headers=self._headers(),
            )
            if r.status_code >= 400:
                raise MediaError(f"video create failed [{r.status_code}]: {r.text[:200]}")
            resp = self._resp_ok(r.json())
            video_id = resp.get("video_id") or resp.get("VideoId")
            if video_id is None:
                raise MediaError("video generation returned no id")
            url = await self._poll_video(client, video_id)
            return await self._download(client, url)

    async def _poll_video(self, client: httpx.AsyncClient, video_id: int) -> str:
        waited = 0
        while waited < settings.media_poll_timeout:
            r = await client.get(
                f"{self.base_url}/openapi/v2/video/result/{video_id}",
                headers=self._headers(),
            )
            if r.status_code < 400:
                resp = self._resp_ok(r.json())
                status = resp.get("status")
                url = resp.get("url") or resp.get("Url")
                # status 1 == complete (5 == still generating)
                if status == 1 and url:
                    return url
                if status in (2, 3, 4, 7, 8):  # failed/timeout/moderation states
                    raise MediaError(f"video {video_id} failed (status {status})")
            await asyncio.sleep(8)
            waited += 8
        raise MediaError(f"video {video_id} timed out")


class GoogleTTSClient:
    """Google Cloud Text-to-Speech (REST, API-key auth)."""

    def __init__(self, api_key: str | None = None) -> None:
        self.api_key = api_key or settings.google_tts_api_key

    @property
    def enabled(self) -> bool:
        return bool(self.api_key)

    async def synthesize(self, text: str) -> bytes:
        body = {
            "input": {"text": text},
            "voice": {
                "languageCode": settings.google_tts_language,
                "name": settings.google_tts_voice,
            },
            "audioConfig": {"audioEncoding": "MP3"},
        }
        async with httpx.AsyncClient(timeout=60) as client:
            r = await client.post(
                "https://texttospeech.googleapis.com/v1/text:synthesize",
                params={"key": self.api_key},
                json=body,
            )
        if r.status_code >= 400:
            raise MediaError(f"tts failed [{r.status_code}]: {r.text[:200]}")
        content = r.json().get("audioContent")
        if not content:
            raise MediaError("tts returned no audio")
        return base64.b64decode(content)


def _asset_name(prefix: str, kind: str, seed: str, ext: str) -> str:
    digest = hashlib.sha1(seed.encode("utf-8")).hexdigest()[:12]  # noqa: S324 — non-crypto id
    return f"{prefix}/assets/{kind}-{digest}.{ext}"


async def _noop(_msg: str, _pct: int) -> None:
    return None


def _iter_blocks(concept: dict):
    for chapter in concept.get("chapters", []):
        pages = chapter.get("pages")
        if pages:
            for page in pages:
                yield from page.get("blocks", [])
        else:
            yield from chapter.get("blocks", [])


def _count_media(concept: dict) -> dict[str, int]:
    counts = {"image": 0, "video": 0, "audio": 0}
    for block in _iter_blocks(concept):
        t = block.get("type")
        if t == "image" and block.get("prompt"):
            counts["image"] += 1
        elif t == "hotspot" and block.get("imagePrompt"):
            counts["image"] += 1
        elif t == "dialogue":
            counts["image"] += sum(1 for s in block.get("speakers", []) if s.get("avatarPrompt"))
        elif t == "video" and block.get("prompt"):
            counts["video"] += 1
        elif t == "audio" and block.get("say"):
            counts["audio"] += 1
    return counts


async def generate_media_for_concept(
    concept: dict,
    prefix: str,
    progress_cb: ProgressCb | None = None,
) -> dict:
    """Mutate `concept` in place, filling media URLs; return it. Best-effort."""
    cb = progress_cb or _noop
    pix = PixverseClient()
    tts = GoogleTTSClient()
    bucket = settings.courses_bucket

    if not (pix.enabled or tts.enabled):
        logger.info("No media providers configured; skipping media pass")
        return concept

    budget = {
        "image": settings.media_max_images,
        "video": settings.media_max_videos,
        "audio": settings.media_max_audio,
    }
    planned = _count_media(concept)
    todo_img = min(planned["image"], budget["image"])
    todo_aud = min(planned["audio"], budget["audio"])
    todo_vid = min(planned["video"], budget["video"])
    done = 0
    total = max(todo_img + todo_aud + todo_vid, 1)

    async def step(kind: str, label: str) -> None:
        nonlocal done
        done += 1
        pct = min(99, int(done / total * 100))
        await cb(f"{label} ({done}/{total})", pct)

    async def gen_image(prompt: str, kind: str, ar: str = "16:9") -> str | None:
        if not pix.enabled or budget["image"] <= 0:
            return None
        budget["image"] -= 1
        try:
            data = await pix.generate_image(prompt, ar)
        except MediaError as exc:
            logger.warning("image gen failed: %s", exc)
            return None
        obj = _asset_name(prefix, kind, prompt, "png")
        put_bytes(data, obj, bucket, "image/png")
        return obj.split(f"{prefix}/", 1)[1]

    async def gen_video(prompt: str) -> str | None:
        if not pix.enabled or budget["video"] <= 0:
            return None
        budget["video"] -= 1
        try:
            data = await pix.generate_video(prompt)
        except MediaError as exc:
            logger.warning("video gen failed: %s", exc)
            return None
        obj = _asset_name(prefix, "video", prompt, "mp4")
        put_bytes(data, obj, bucket, "video/mp4")
        return obj.split(f"{prefix}/", 1)[1]

    async def gen_audio(text: str) -> str | None:
        if not tts.enabled or budget["audio"] <= 0:
            return None
        budget["audio"] -= 1
        try:
            data = await tts.synthesize(text)
        except MediaError as exc:
            logger.warning("tts failed: %s", exc)
            return None
        obj = _asset_name(prefix, "audio", text, "mp3")
        put_bytes(data, obj, bucket, "audio/mpeg")
        return obj.split(f"{prefix}/", 1)[1]

    for block in _iter_blocks(concept):
        t = block.get("type")
        if t == "image" and block.get("prompt") and not block.get("url"):
            url = await gen_image(block["prompt"], "image")
            if url:
                block["url"] = url
            await step("image", "Generating illustration")
        elif t == "hotspot" and block.get("imagePrompt") and not block.get("imageUrl"):
            url = await gen_image(block["imagePrompt"], "hotspot")
            if url:
                block["imageUrl"] = url
            await step("image", "Generating diagram")
        elif t == "dialogue":
            for sp in block.get("speakers", []):
                if sp.get("avatarPrompt") and not sp.get("avatarUrl"):
                    url = await gen_image(sp["avatarPrompt"], "avatar", "1:1")
                    if url:
                        sp["avatarUrl"] = url
                    await step("image", "Generating avatar")
        elif t == "video" and block.get("prompt") and not block.get("url"):
            await cb(
                "Rendering video clip (this can take a minute)…",
                min(99, int(done / total * 100)),
            )
            url = await gen_video(block["prompt"])
            if url:
                block["url"] = url
            await step("video", "Rendering video clip")
        elif t == "audio" and block.get("say") and not block.get("url"):
            url = await gen_audio(block["say"])
            if url:
                block["url"] = url
            await step("audio", "Synthesizing narration")

    return concept
